name: Build application

on:
  push:
    branches: [ '*', '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run linters
        run: |
          pipenv run mypy ./src

      - name: Run tests
        run: |
          pipenv run python setup.py install
          pipenv run pytest